Ruby 3.0 compatibility
Before this change, running the task with Ruby 3.0 failed:

    $ bundle e rake profile:memory
    rake aborted!
    NoMethodError: private method `puts' called for {:scale_bytes=>true, :normalize_paths=>true}:Hash
    /Users/dentarg/.gem/ruby/3.0.0/gems/memory_profiler-1.0.0/lib/memory_profiler/results.rb:131:in `pretty_print'
    tasks/profile.rake:24:in `block (2 levels) in <top (required)>'
    /Users/dentarg/.gem/ruby/3.0.0/bin/bundle:23:in `load'
    /Users/dentarg/.gem/ruby/3.0.0/bin/bundle:23:in `<main>'
    Tasks: TOP => profile:memory
    (See full trace by running task with --trace)